plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ksp)

    alias(libs.plugins.aboutlibraries)

    alias(libs.plugins.versions)
    alias(libs.plugins.detekt)
    alias(libs.plugins.ktlint)
}

apply from: "${projectDir}/gradle/utils.gradle"

def appVersionMajor = libs.versions.appVersionMajor.get().toInteger()
def appVersionMinor = libs.versions.appVersionMinor.get().toInteger()
def appVersionPatch = libs.versions.appVersionPatch.get().toInteger()

android {
    namespace "me.proxer.app"
    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        applicationId "me.proxer.app"
        minSdk libs.versions.minSdk.get().toInteger()
        targetSdk libs.versions.targetSdk.get().toInteger()
        versionCode appVersionMajor * 1000000 + appVersionMinor * 10000 + appVersionPatch * 100
        versionName "$appVersionMajor.$appVersionMinor.$appVersionPatch"

        vectorDrawables.useSupportLibrary true
        resourceConfigurations += ["de"]
    }

    buildFeatures {
        buildConfig true
    }

    sourceSets {
        main {
            java.srcDirs += "src/main/kotlin"
        }

        debug {
            java.srcDirs += "src/debug/kotlin"
        }

        release {
            java.srcDirs += "src/release/kotlin"
        }

        logRelease {
            java.srcDirs = release.java.srcDirs
            res.srcDirs = release.res.srcDirs
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    signingConfigs {
        if (shouldSign()) {
            release {
                storeFile file(getFromSecrets("RELEASE_STORE_FILE"))
                storePassword getFromSecrets("RELEASE_STORE_PASSWORD")
                keyAlias getFromSecrets("RELEASE_KEY_ALIAS")
                keyPassword getFromSecrets("RELEASE_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        if (!shouldSign() && !isCI()) {
            logger.warn("This build will not be signed because it is missing the keystore info. Please add " +
                    "values for \"RELEASE_STORE_FILE\", \"RELEASE_STORE_PASSWORD\", \"RELEASE_KEY_ALIAS\" and " +
                    "\"RELEASE_KEY_PASSWORD\" to your secrets.properties file if you want the apk to be signed.")
        }

        debug {
            ndk { abiFilters "arm64-v8a", "armeabi-v7a", "x86_64", "x86" }

            versionNameSuffix = "-debug"
            buildConfigField "String", "PROXER_API_KEY", "\"${getFromSecrets("PROXER_API_KEY")}\""
            buildConfigField "boolean", "LOG", "Boolean.parseBoolean(\"true\")"
        }

        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "config/shrinker/shrinker-rules.pro"

            ndk { abiFilters "arm64-v8a", "armeabi-v7a", "x86_64", "x86" }

            buildConfigField "String", "PROXER_API_KEY", "\"${getFromSecrets("PROXER_API_KEY")}\""
            buildConfigField "boolean", "LOG", "Boolean.parseBoolean(\"false\")"

            if (shouldSign()) {
                signingConfig signingConfigs.release
            }
        }

        logRelease {
            initWith release
            matchingFallbacks = ["release"]

            versionNameSuffix = "-logRelease-${getGitHash()}"
            buildConfigField "boolean", "LOG", "Boolean.parseBoolean(\"true\")"
        }
    }

    lint {
        warningsAsErrors = true
        checkReleaseBuilds = false

        lintConfig = file("$rootDir/config/lint/lint.xml")
        xmlOutput = file("$buildDir/reports/lint/lint-results.xml")
        htmlOutput = file("$buildDir/reports/lint/lint-results.html")
    }

    packaging {
        jniLibs {
            useLegacyPackaging = false
        }

        resources {
            excludes += [
                    "META-INF/*.kotlin_module",
                    "META-INF/*.version",
                    "META-INF/rxkotlin.properties",
                    "META-INF/proguard/**",
                    "META-INF/README.md",
                    "META-INF/nanohttpd/**",
                    "kotlin/**",
                    "kotlinx/**",
                    "third_party/**",
                    "jsr305_annotations/**",
                    "error_prone/**",
                    "auto/**",
                    "build-data.properties",
                    "androidsupportmultidexversion.txt",
                    "play-services-*.properties"
            ]
        }
    }

    bundle {
        language {
            enableSplit = false
        }
    }

    applicationVariants.all { variant ->
        def suffix = variant.buildType.name == "release" ? "-release" : ""

        variant.outputs.all {
            outputFileName = "app-${variant.versionName}${suffix}.apk"
        }
    }
}

kotlin {
    jvmToolchain(17)

    compilerOptions {
        freeCompilerArgs.addAll("-Xjsr305=strict")
    }
}

ksp {
    arg("room.schemaLocation", "$projectDir/schemas".toString())
    arg("room.incremental", "true")
}

dependencies {
    implementation libs.kotlin.stdlib
    implementation libs.koin.android

    implementation libs.play.app.update
    implementation libs.play.services.cast.framework
    implementation libs.play.services.ads.identifier
    implementation(libs.interactivemedia) {
        version { strictly libs.versions.interactiveMedia.get() }
    }

    implementation libs.androidx.appcompat
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.browser
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.lifecycle.process
    implementation libs.androidx.lifecycle.common.java8
    implementation libs.androidx.room.runtime
    implementation libs.androidx.room.rxjava2
    implementation libs.androidx.work.runtime.ktx
    implementation libs.androidx.core.ktx
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.sharetarget
    implementation libs.androidx.security.crypto

    implementation libs.rxjava
    implementation libs.rxkotlin
    implementation libs.rxandroid
    implementation libs.rxbinding.core
    implementation libs.rxbinding.appcompat
    implementation libs.rxbinding.recyclerview
    implementation libs.rxbinding.swiperefreshlayout
    implementation libs.rxbinding.material
    implementation libs.rx.preferences
    implementation libs.rxbus
    implementation libs.autodispose.ktx
    implementation libs.autodispose.android.archcomponents.ktx

    implementation libs.androidx.recyclerview
    implementation libs.androidx.cardview
    implementation libs.androidx.gridlayout
    implementation libs.androidx.viewpager2
    implementation libs.androidx.swiperefreshlayout
    implementation libs.androidx.exifinterface
    implementation libs.androidx.constraintlayout
    implementation libs.material
    implementation libs.androidx.preference
    implementation libs.support.preference
    implementation libs.support.spinner
    implementation libs.iconics.core
    implementation libs.iconics.views
    implementation libs.community.material.typeface
    implementation libs.materialdrawer
    implementation libs.materialdrawer.iconics
    implementation libs.aboutlibraries
    implementation(libs.crossfader) { artifact { type = "aar" } }
    implementation libs.material.about.library
    implementation libs.subsampling.scale.image.view
    implementation libs.subsampling.pdf.decoder
    implementation libs.material.dialogs.core
    implementation libs.flexbox
    implementation libs.emoji.ios
    implementation libs.materialprogressbar
    implementation libs.materialratingbar
    implementation libs.customtabshelper
    implementation libs.introduction
    implementation libs.aspect.ratio.imageview
    implementation libs.gravitysnaphelper
    implementation libs.exoplayer
    implementation libs.exoplayer.cast
    implementation libs.exoplayer.okhttp
    implementation libs.exoplayer.ima
    implementation libs.previewseekbar
    implementation libs.previewseekbar.exoplayer

    implementation libs.proxerlib
    implementation libs.threetenabp
    implementation libs.glide
    implementation libs.glide.okhttp3
    implementation libs.retrofit
    implementation libs.okhttp
    implementation libs.okhttp.brotli
    implementation libs.okhttp.logging
    implementation libs.okio
    implementation libs.moshi
    implementation libs.moshi.adapters
    implementation libs.easy.header.footer.adapter
    implementation libs.koptional.rxjava2
    implementation libs.kotterknife
    implementation libs.image.core
    implementation libs.image.jpeg
    implementation libs.image.png
    implementation libs.better.link.movement.method
    implementation libs.jsoup

    implementation libs.hawk

    implementation libs.strictmodecompat
    implementation libs.timber
    implementation libs.anrwatchdog

    implementation libs.leakcanary.plumber
    debugImplementation libs.leakcanary

    releaseImplementation libs.customactivityoncrash
    logReleaseImplementation libs.customactivityoncrash

    ksp libs.androidx.room.compiler
    ksp libs.glide.ksp
    ksp libs.moshi.codegen

    compileOnly libs.javax.annotation
}

configurations.configureEach {
    resolutionStrategy.dependencySubstitution {
        // The jitpack builds of these artifacts and the jcenter artifacts below are no longer available.
        substitute module("com.squareup.moshi:moshi") using module("com.squareup.moshi:moshi:${libs.versions.moshi.get()}")
        substitute module("com.google.android:flexbox") using module("com.google.android.flexbox:flexbox:${libs.versions.flexbox.get()}")
        substitute module("com.gojuno.koptional:koptional") using module("com.github.gojuno.koptional:koptional:${libs.versions.koptional.get()}")
        substitute module("com.gojuno.koptional:koptional-rxjava2-extensions") using module("com.github.gojuno.koptional:koptional-rxjava2-extensions:${libs.versions.koptional.get()}")
    }
}

detekt {
    toolVersion = libs.versions.detekt.get()
    buildUponDefaultConfig = true

    config.setFrom(files("$projectDir/config/detekt/detekt.yml"))
}

tasks.withType(io.gitlab.arturbosch.detekt.Detekt).configureEach {
    jvmTarget = "17"

    reports {
        xml.required = true
        xml.outputLocation = file("$buildDir/reports/detekt/detekt.xml")
        html.required = true
        html.outputLocation = file("$buildDir/reports/detekt/detekt.html")
    }
}

ktlint {
    version = libs.versions.ktlint.get()
    reporters {
        reporter org.jlleitschuh.gradle.ktlint.reporter.ReporterType.CHECKSTYLE
    }
}

tasks.named("dependencyUpdates").configure {
    rejectVersionIf {
        it.candidate.version.contains("alpha")
    }
}
