package me.proxer.app.settings

import android.app.Activity
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import com.mikepenz.aboutlibraries.ui.compose.android.produceLibraries
import com.mikepenz.aboutlibraries.ui.compose.m3.LibrariesContainer
import me.proxer.app.R
import me.proxer.app.base.ComposeActivity
import me.proxer.app.ui.components.ProxerScaffold
import me.proxer.app.ui.shell.LocalAppNavigator
import me.proxer.app.util.extension.startActivity

/**
 * The licenses of the libraries used in the app, generated by the AboutLibraries plugin.
 */
class ProxerLibsActivity : ComposeActivity() {

    companion object {
        fun navigateTo(context: Activity) = context.startActivity<ProxerLibsActivity>()
    }

    @Composable
    override fun Content() {
        val navigator = LocalAppNavigator.current
        val libraries by produceLibraries(R.raw.aboutlibraries)

        ProxerScaffold(
            title = stringResource(R.string.about_licenses_activity_title),
            onNavigateUp = navigator::navigateUp
        ) { padding ->
            LibrariesContainer(libraries = libraries, modifier = Modifier.fillMaxSize(), contentPadding = padding)
        }
    }
}
