#!/usr/bin/env python3
"""
Generates the Material 3 color schemes for the theme presets (Classic, Blue-Green, Gloomy).

The same schemes are written for Compose (PresetColorSchemes.kt) and for the View system (colors_presets.xml and
themes_presets.xml), so both UI toolkits use identical colors on every API level. The Dynamic preset uses the system
colors on Android 12+ and falls back to Classic below that, so it needs no generated scheme.

Usage (requires the "materialyoucolor" package, e.g. in a virtualenv):
    pip install materialyoucolor==3.0.4
    python3 scripts/generate_color_schemes.py
"""

from pathlib import Path

from materialyoucolor.dynamiccolor.dynamic_scheme import DynamicScheme
from materialyoucolor.dynamiccolor.material_dynamic_colors import MaterialDynamicColors
from materialyoucolor.dynamiccolor.variant import Variant
from materialyoucolor.hct import Hct
from materialyoucolor.palettes.tonal_palette import TonalPalette

ROOT = Path(__file__).resolve().parent.parent
KOTLIN_FILE = ROOT / "src/main/kotlin/me/proxer/app/ui/theme/PresetColorSchemes.kt"
COLORS_FILE = ROOT / "src/main/res/values/colors_presets.xml"
COLORS_NIGHT_FILE = ROOT / "src/main/res/values-night/colors_presets.xml"
THEMES_FILE = ROOT / "src/main/res/values/themes_presets.xml"

SPEC = "2021"

# name, seed color, variant, optional tertiary seed, XML theme name.
PRESETS = [
    ("classic", 0xFF8A0E0E, Variant.CONTENT, None, "Theme.App"),
    ("blue_green", 0xFF1565C0, Variant.FIDELITY, 0xFF00796B, "Theme.App.BG"),
    ("gloomy", 0xFF263238, Variant.NEUTRAL, None, "Theme.App.Gloomy"),
]

# Material color role, XML theme attribute (None if there is none) and Compose ColorScheme parameter (None if there
# is none).
ROLES = [
    ("primary", "colorPrimary", "primary"),
    ("onPrimary", "colorOnPrimary", "onPrimary"),
    ("primaryContainer", "colorPrimaryContainer", "primaryContainer"),
    ("onPrimaryContainer", "colorOnPrimaryContainer", "onPrimaryContainer"),
    ("inversePrimary", "colorPrimaryInverse", "inversePrimary"),
    ("primaryFixed", "colorPrimaryFixed", None),
    ("primaryFixedDim", "colorPrimaryFixedDim", None),
    ("onPrimaryFixed", "colorOnPrimaryFixed", None),
    ("onPrimaryFixedVariant", "colorOnPrimaryFixedVariant", None),
    ("secondary", "colorSecondary", "secondary"),
    ("onSecondary", "colorOnSecondary", "onSecondary"),
    ("secondaryContainer", "colorSecondaryContainer", "secondaryContainer"),
    ("onSecondaryContainer", "colorOnSecondaryContainer", "onSecondaryContainer"),
    ("secondaryFixed", "colorSecondaryFixed", None),
    ("secondaryFixedDim", "colorSecondaryFixedDim", None),
    ("onSecondaryFixed", "colorOnSecondaryFixed", None),
    ("onSecondaryFixedVariant", "colorOnSecondaryFixedVariant", None),
    ("tertiary", "colorTertiary", "tertiary"),
    ("onTertiary", "colorOnTertiary", "onTertiary"),
    ("tertiaryContainer", "colorTertiaryContainer", "tertiaryContainer"),
    ("onTertiaryContainer", "colorOnTertiaryContainer", "onTertiaryContainer"),
    ("tertiaryFixed", "colorTertiaryFixed", None),
    ("tertiaryFixedDim", "colorTertiaryFixedDim", None),
    ("onTertiaryFixed", "colorOnTertiaryFixed", None),
    ("onTertiaryFixedVariant", "colorOnTertiaryFixedVariant", None),
    ("error", "colorError", "error"),
    ("onError", "colorOnError", "onError"),
    ("errorContainer", "colorErrorContainer", "errorContainer"),
    ("onErrorContainer", "colorOnErrorContainer", "onErrorContainer"),
    ("background", "android:colorBackground", "background"),
    ("onBackground", "colorOnBackground", "onBackground"),
    ("surface", "colorSurface", "surface"),
    ("onSurface", "colorOnSurface", "onSurface"),
    ("surfaceVariant", "colorSurfaceVariant", "surfaceVariant"),
    ("onSurfaceVariant", "colorOnSurfaceVariant", "onSurfaceVariant"),
    ("surfaceTint", None, "surfaceTint"),
    ("inverseSurface", "colorSurfaceInverse", "inverseSurface"),
    ("inverseOnSurface", "colorOnSurfaceInverse", "inverseOnSurface"),
    ("outline", "colorOutline", "outline"),
    ("outlineVariant", "colorOutlineVariant", "outlineVariant"),
    ("scrim", None, "scrim"),
    ("surfaceBright", "colorSurfaceBright", "surfaceBright"),
    ("surfaceDim", "colorSurfaceDim", "surfaceDim"),
    ("surfaceContainerLowest", "colorSurfaceContainerLowest", "surfaceContainerLowest"),
    ("surfaceContainerLow", "colorSurfaceContainerLow", "surfaceContainerLow"),
    ("surfaceContainer", "colorSurfaceContainer", "surfaceContainer"),
    ("surfaceContainerHigh", "colorSurfaceContainerHigh", "surfaceContainerHigh"),
    ("surfaceContainerHighest", "colorSurfaceContainerHighest", "surfaceContainerHighest"),
]

HEADER = "Generated by scripts/generate_color_schemes.py. Do not edit by hand."


def snake_case(name):
    return "".join("_" + c.lower() if c.isupper() else c for c in name)


def camel_case(name):
    return "".join(part.capitalize() for part in name.split("_"))


def scheme(seed, variant, tertiary_seed, is_dark):
    tertiary_palette = TonalPalette.from_hct(Hct.from_int(tertiary_seed)) if tertiary_seed else None

    return DynamicScheme(
        source_color_hct=Hct.from_int(seed),
        variant=variant,
        contrast_level=0.0,
        is_dark=is_dark,
        spec_version=SPEC,
        tertiary_palette=tertiary_palette,
    )


def colors(dynamic_scheme):
    material_colors = MaterialDynamicColors(spec=SPEC)

    return {role: getattr(material_colors, role).get_argb(dynamic_scheme) & 0xFFFFFFFF for role, _, _ in ROLES}


def xml_color_name(preset, role):
    return f"preset_{preset}_{snake_case(role)}"


def write_colors(path, schemes, is_dark):
    lines = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {HEADER} -->", "<resources>"]

    for preset, *_ in PRESETS:
        values = schemes[(preset, is_dark)]

        for role, xml_attr, _ in ROLES:
            if xml_attr is not None:
                lines.append(f'    <color name="{xml_color_name(preset, role)}">#{values[role] & 0xFFFFFF:06X}</color>')

        lines.append("")

    lines[-1] = "</resources>"
    path.write_text("\n".join(lines) + "\n")


def write_themes(path):
    lines = ['<?xml version="1.0" encoding="utf-8"?>', f"<!-- {HEADER} -->", "<resources>", ""]

    for preset, _, _, _, theme_name in PRESETS:
        parent = "Base.Theme.App.DayNight" if theme_name == "Theme.App" else "Theme.App"
        lines.append(f'    <style name="{theme_name}" parent="{parent}">')

        for role, xml_attr, _ in ROLES:
            if xml_attr is not None:
                lines.append(f'        <item name="{xml_attr}">@color/{xml_color_name(preset, role)}</item>')

        lines.append("    </style>")
        lines.append("")

    lines.append("</resources>")
    path.write_text("\n".join(lines) + "\n")


def write_kotlin(path, schemes):
    lines = [
        "package me.proxer.app.ui.theme",
        "",
        "import androidx.compose.material3.darkColorScheme",
        "import androidx.compose.material3.lightColorScheme",
        "import androidx.compose.ui.graphics.Color",
        "",
        f"// {HEADER}",
    ]

    for preset, *_ in PRESETS:
        for is_dark in (False, True):
            values = schemes[(preset, is_dark)]
            name = f"{camel_case(preset)}{'Dark' if is_dark else 'Light'}ColorScheme"
            factory = "darkColorScheme" if is_dark else "lightColorScheme"

            lines.append("")
            lines.append(f"internal val {name} = {factory}(")

            for role, _, compose_param in ROLES:
                if compose_param is not None:
                    lines.append(f"    {compose_param} = Color(0x{values[role]:08X}),")

            lines.append(")")

    path.write_text("\n".join(lines) + "\n")


def main():
    schemes = {}

    for preset, seed, variant, tertiary_seed, _ in PRESETS:
        for is_dark in (False, True):
            schemes[(preset, is_dark)] = colors(scheme(seed, variant, tertiary_seed, is_dark))

    KOTLIN_FILE.parent.mkdir(parents=True, exist_ok=True)

    write_colors(COLORS_FILE, schemes, is_dark=False)
    write_colors(COLORS_NIGHT_FILE, schemes, is_dark=True)
    write_themes(THEMES_FILE)
    write_kotlin(KOTLIN_FILE, schemes)


if __name__ == "__main__":
    main()
